# Generated by Django 4.2.30 on 2026-06-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_carrier_order_delivery_slot_order_gift_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_tags',
            field=models.CharField(blank=True, default='', help_text='AI auto-detected tags (comma-separated)', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferences_json',
            field=models.TextField(blank=True, default='{}', help_text='AI Personal Shopper preferences (JSON format)'),
        ),
    ]
