# Generated by Django 4.2.30 on 2026-06-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_ai_tags_userprofile_preferences_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company_gstin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='is_b2b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='subscription_period',
            field=models.CharField(blank=True, help_text='monthly or annual', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='e.g. 10x5x15 cm', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_material',
            field=models.CharField(blank=True, help_text='e.g. Stainless Steel, Cotton', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_info',
            field=models.CharField(blank=True, help_text='e.g. 1 Year Brand Warranty', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, help_text='e.g. 500g', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activity_log_json',
            field=models.TextField(blank=True, default='[]', help_text='User activity logs (JSON format)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='biometric_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_cards_json',
            field=models.TextField(blank=True, default='[]', help_text='Saved cards details (JSON format)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_upi_json',
            field=models.TextField(blank=True, default='[]', help_text='Saved UPI IDs (JSON format)'),
        ),
    ]
